# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic', '0002_remove_resource_namespace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='id',
        ),
        migrations.AlterField(
            model_name='resource',
            name='subject',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
