# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic', '0003_auto_20160420_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='subject',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
