# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic', '0004_auto_20160420_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('value', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Predicate',
            fields=[
                ('value', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
    ]
