# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic', '0005_klass_predicate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('value', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='klass',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
