# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic', '0006_auto_20160429_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssertedStatement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('termcomb', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'kb_2cba3dacfc_asserted_statements',
                'managed': False,
            },
        ),
    ]
