# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semantic', '0007_assertedstatement'),
        ('aspect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspect',
            name='classes',
            field=models.ManyToManyField(to='semantic.Klass'),
        ),
    ]
